version: '3.8'

services:
  pokemon-app:
    build: .
    container_name: pokemon-search-app
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules 